apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-store-deployment
  labels:
    app: file-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-store
  template:
    metadata:
      labels:
        app: file-store
    spec:
      containers:
      - name: file-store
        image: sghadi1203/file-store:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: file-store-service
spec:
  selector:
    app: file-store
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32323
